// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: userdata.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHashReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *GetHashReq) Reset() {
	*x = GetHashReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashReq) ProtoMessage() {}

func (x *GetHashReq) ProtoReflect() protoreflect.Message {
	mi := &file_userdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashReq.ProtoReflect.Descriptor instead.
func (*GetHashReq) Descriptor() ([]byte, []int) {
	return file_userdata_proto_rawDescGZIP(), []int{0}
}

func (x *GetHashReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHashReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type GetHashResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GetHashResp) Reset() {
	*x = GetHashResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashResp) ProtoMessage() {}

func (x *GetHashResp) ProtoReflect() protoreflect.Message {
	mi := &file_userdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashResp.ProtoReflect.Descriptor instead.
func (*GetHashResp) Descriptor() ([]byte, []int) {
	return file_userdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetHashResp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CheckHashReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *CheckHashReq) Reset() {
	*x = CheckHashReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHashReq) ProtoMessage() {}

func (x *CheckHashReq) ProtoReflect() protoreflect.Message {
	mi := &file_userdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHashReq.ProtoReflect.Descriptor instead.
func (*CheckHashReq) Descriptor() ([]byte, []int) {
	return file_userdata_proto_rawDescGZIP(), []int{2}
}

func (x *CheckHashReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CheckHashReq) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type CheckHashResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp bool `protobuf:"varint,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *CheckHashResp) Reset() {
	*x = CheckHashResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHashResp) ProtoMessage() {}

func (x *CheckHashResp) ProtoReflect() protoreflect.Message {
	mi := &file_userdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHashResp.ProtoReflect.Descriptor instead.
func (*CheckHashResp) Descriptor() ([]byte, []int) {
	return file_userdata_proto_rawDescGZIP(), []int{3}
}

func (x *CheckHashResp) GetResp() bool {
	if x != nil {
		return x.Resp
	}
	return false
}

var File_userdata_proto protoreflect.FileDescriptor

var file_userdata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x36,
	0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x32, 0x6a, 0x0a, 0x06, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48,
	0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userdata_proto_rawDescOnce sync.Once
	file_userdata_proto_rawDescData = file_userdata_proto_rawDesc
)

func file_userdata_proto_rawDescGZIP() []byte {
	file_userdata_proto_rawDescOnce.Do(func() {
		file_userdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_userdata_proto_rawDescData)
	})
	return file_userdata_proto_rawDescData
}

var file_userdata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userdata_proto_goTypes = []interface{}{
	(*GetHashReq)(nil),    // 0: api.GetHashReq
	(*GetHashResp)(nil),   // 1: api.GetHashResp
	(*CheckHashReq)(nil),  // 2: api.CheckHashReq
	(*CheckHashResp)(nil), // 3: api.CheckHashResp
}
var file_userdata_proto_depIdxs = []int32{
	0, // 0: api.Hasher.GetHash:input_type -> api.GetHashReq
	2, // 1: api.Hasher.CheckHash:input_type -> api.CheckHashReq
	1, // 2: api.Hasher.GetHash:output_type -> api.GetHashResp
	3, // 3: api.Hasher.CheckHash:output_type -> api.CheckHashResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userdata_proto_init() }
func file_userdata_proto_init() {
	if File_userdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHashResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHashReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHashResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userdata_proto_goTypes,
		DependencyIndexes: file_userdata_proto_depIdxs,
		MessageInfos:      file_userdata_proto_msgTypes,
	}.Build()
	File_userdata_proto = out.File
	file_userdata_proto_rawDesc = nil
	file_userdata_proto_goTypes = nil
	file_userdata_proto_depIdxs = nil
}
